version: "3.7"

services:
  wiremock:
    image: rodolpheche/wiremock:latest
    volumes:
      - ./tests/wiremock:/home/wiremock:ro
    env_file: [.env]
    command: "--global-response-templating"
    ports: ["${WIREMOCK_PORT}:8080"]
